language: php
php:
- 5.6
script:
- phpunit -c tests/phpunit.xml
deploy:
  provider: heroku
  api_key:
    secure: e0qD6jlcbn8F/bfmL794WKstqF9FAyA8qJvrtuzwQS2bnmjTDAKcoA+fxrN9oEoBGyf+QcKUySiBDlG8S2cZPz5M5LicpZBJFJANAXd9jiTJQsyFrpJqh+56uwGJwnpfHTlCWAe++3xy6gXZffnKU5QFGFelhx5s1lLfgwIXHsM=
  app:
    master: phunconf-org
    development: development-phunconf-org
  on:
    repo: sydphp/phunconf.org
