<?php
$bodyClass = 'homepage';
?>
<!-- Banner -->

<div id="banner">
    <div class="container">
        <section>
            <header>
                <h2>5th Feb 2015</h2>
                <span class="byline">5th Annual <span class="brand" >Syd<span class="php">PHP</span></span> <span class="phunconf">Phunconference</span></span>
            </header>
            <a href="https://phunconf5.eventbrite.com.au" target="_blank" class="button">Book&nbsp;now</a>
        </section>
    </div>
</div>

<!-- Intro -->
<div id="intro">
    <div class="container">
        <div class="row">

            <section class="6u">
                <header>
                    <h2>Phunconf 5.0</h2>
                </header>
                <div class="content">
                    <p>SydPHP is proud to announce our 5th annual Phunconference,
                        affectionately known to the local community as Phunconf! We invite
                        developers of all PHP and related expertise to join us on February
                        5th for a series of workshops, a code retreat followed by our famous
                        unconf in the evening.

                    </p>

                    <p>
                        Phunconf is a non profit event run by organisers of the Sydney PHP
                        User Group (SydPHP) for the benefit of the local development
                        community.
                    </p>
                </div>
            </section>

            <section class="4u">

                <span class="image">
                    <img class="promo" src="img/phunconf4.0-group2.png" alt="">
                </span>


            </section>


        </div>
    </div>
</div>

<!-- Main -->
<div id="main">
    <div class="container"><!-- Row #1 -->
        <!-- <div class="row"> -->
        <section>
            <h3>Phunconf is run for the benefit of the Sydney PHP community by SydPHP organisers:</h3>
            <ul class="featured">
                <li><p><a href="http://www.meetup.com/SydPHP/members/49626422/">Dave Clark</a></p>
                    <a href="http://www.meetup.com/SydPHP/members/49626422/">
                        <img class="team" src="/img/team/dave.jpg" alt="Dave Clark profile"/>
                    </a>
                </li>
                <li><p><a href="http://www.meetup.com/SydPHP/members/32702732/">Jack Skinner</a></p>
                    <a href="http://www.meetup.com/SydPHP/members/32702732/">
                        <img class="team" src="/img/team/jack.jpg" alt="Jack Skinner profile"/>
                    </a></li>
                <li><p><a href="http://www.meetup.com/SydPHP/members/13462493/">Dean Rather</a></p>
                    <a href="http://www.meetup.com/SydPHP/members/13462493/">
                        <img class="team" src="/img/team/dean.jpg" alt="Dean Rather profile"/>
                    </a></li>
                <li><p><a href="http://www.meetup.com/SydPHP/members/49008392/">Justin King</a></p>
                    <a href="http://www.meetup.com/SydPHP/members/49008392/">
                        <img class="team" src="/img/team/justin.jpg" alt="Justin King profile"/>
                    </a>
                </li>
            </ul>
            <section>
                <!--  </div> -->
    </div>
</div>
