<?php
$bodyClass = 'homepage';
?>
<!-- Banner -->

<script src="/js/jquery.plugin.min.js"></script>
<script src="/js/jquery.countdown.min.js"></script>
<link rel="stylesheet" href="/css/jquery.countdown.css" />

<div id="banner">
    <div class="container">
        <section>
            <header>
                <h2>5th Feb 2015</h2>
                <span class="byline">5th Annual <span class="brand" >Syd<span class="php">PHP</span></span> <span class="phunconf">Phunconference</span></span>
            </header>

            <div id="buyNow">
                <div class="container"></div>
            </div>
            
            <script type="text/javascript" language="javascript">
            //ticketOnSaleTime = new Date((new Date()).getTime() + 1000*3); //  retain f
            var ticketOnSaleTime= new Date("January 9, 2015 18:06:20");
            $('#buyNow .container').countdown({
                until: ticketOnSaleTime,
                description: "Tickets on sale",
                expiryText: '<a href="https://phunconf5.eventbrite.com.au" target="_blank" class="button" style="display: none">Book&nbsp;now</a>',
                onExpiry: function () {
                    setTimeout(function() {
                        $('#buyNow .container .button').fadeIn(2000);
                    }, 300);

                }
            });
            </script>

        </section>
    </div>
</div>

<!-- Intro -->
<div id="intro">
    <div class="container">
        <div class="row">

            <section class="6u">
                <header>
                    <h2>Unconf</h2>
                </header>
                <div class="content">
                    <p>
                        A series of open circle discussions focusing on knowledge sharing and peer learning.  A wide range of topics are discussed and no unconf is ever the same.
                    </p>
                </div>
                <header>
                    <h2>Workshops</h2>
                </header>
                <div class="content">
                    <p>
                        Workshops sizes are limited for the benefit of those attending.  Sessions include PHP Security and Web Applications at Scale as well as a PHP Masterclass.
                    </p>
                </div>
                <header>
                    <h2>Code Retreat</h2>
                </header>
                <div class="content">
                    <p>
                        An opportunity for developers to hone their unit testing skills.  This is a unique and hands on pair programming experience.
                    </p>
                </div>
            </section>

            <section class="4u">

                <span class="image">
                    <img class="promo" src="img/phunconf4.0-group.jpg" alt="">
                </span>

                <span class="image">
                    <img class="promo" src="img/phunconf4.0-circle.jpg" alt="">
                </span>

            </section>
        </div>
    </div>
</div>

<!-- Main -->
<div id="main">
    <div class="container"><!-- Row #1 -->
        <!-- <div class="row"> -->
        <section>
            <h3>Phunconf is run for the benefit of the Sydney PHP community by SydPHP organisers:</h3>
            <ul class="featured">
                <li><p><a href="http://www.meetup.com/SydPHP/members/49626422/">Dave Clark</a></p>
                    <a href="http://www.meetup.com/SydPHP/members/49626422/">
                        <img class="team" src="/img/team/dave.jpg" alt="Dave Clark profile"/>
                    </a>
                </li>
                <li><p><a href="http://www.meetup.com/SydPHP/members/32702732/">Jack Skinner</a></p>
                    <a href="http://www.meetup.com/SydPHP/members/32702732/">
                        <img class="team" src="/img/team/jack.jpg" alt="Jack Skinner profile"/>
                    </a></li>
                <li><p><a href="http://www.meetup.com/SydPHP/members/13462493/">Dean Rather</a></p>
                    <a href="http://www.meetup.com/SydPHP/members/13462493/">
                        <img class="team" src="/img/team/dean.jpg" alt="Dean Rather profile"/>
                    </a></li>
                <li><p><a href="http://www.meetup.com/SydPHP/members/49008392/">Justin King</a></p>
                    <a href="http://www.meetup.com/SydPHP/members/49008392/">
                        <img class="team" src="/img/team/justin.jpg" alt="Justin King profile"/>
                    </a>
                </li>
            </ul>
            <section>
                <!--  </div> -->
    </div>
</div>
