<!-- Intro -->
<div id="intro">
    <div class="container">
        <div class="row">

            <section class="12u">
                <header>
                    <h1>Phunconf Schedule</h1>
                </header>

                <table id="schedule">
                    <thead>
                        <tr>
                            <td></td>
                            <td><h2>Workshops</h2></td>
                            <td><h2>Code Retreat</h2></td>
                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <td class="schedule-time">9:15am</td>
                            <td class="combined-track" colspan="2">Registration Opens<br><em>Morning Tea</em></td>
                        </tr>
                        <tr>
                            <td class="schedule-time">9:40am</td>
                            <td class="combined-track" colspan="2">Tech Setup & Morning Standup</td>
                        </tr>
                        <tr>
                            <td class="schedule-time">10:00am</td>
                            <td class="workshop-track">
                                <h3>Workshop Session 1</h3>
                                <p><strong>PHP masterclass</strong> is a workshop for developers aiming
                                    to master the PHP language and pass the Zend Certification exam.</p>
                            </td>
                            <td class="retreat-track">
                                <h3>Code Retreat Sprint 1 - 3</h3>
                                <p><strong>Code Retreat</strong> is an opportunity (and a challenge) to perfect the art
                                    of Test Driven Development (TDD).</p>
                            </td>
                        </tr>

                        <tr>
                            <td class="schedule-time">12:00pm</td>
                            <td class="combined-track" colspan="2">Lunch</td>
                        </tr>
                        <tr>
                            <td class="schedule-time">12:30pm</td>
                            <td class="workshop-track">
                                <h3>Workshop Session 2</h3>
                                <p><strong>PHP Security</strong> is a hands on workshop exploring the most common security flaws and strategies (and code!) you can apply to fix them.</p>
                            </td>
                            <td class="retreat-track">
                                <h3>Code Retreat Sprint 4 - 6</h3>
                                <p><strong>Code Retreat</strong> is an opportunity (and a challenge) to perfect the art
                                    of Test Driven Development (TDD).</p>
                            </td>
                        </tr>

                        <tr>
                            <td class="schedule-time">2:30pm</td>
                            <td class="combined-track" colspan="2">Afternoon tea</td>
                        </tr>

                        <tr>
                            <td class="schedule-time">2:45pm</td>
                            <td class="workshop-track">
                                <h3>Workshop Session 3</h3>
                                <p><strong>PHP at Scale</strong> is a workshop focused on building SOA and API focused applications.</p>
                            </td>
                            <td class="retreat-track">
                                <h3>Code Retreat Sprint 7 - 9</h3>
                                <p><strong>Code Retreat</strong> is an opportunity (and a challenge) to perfect the art
                                    of Test Driven Development (TDD).</p>
                            </td>
                        </tr>

                        <tr>
                            <td class="schedule-time">4:45pm</td>
                            <td class="combined-track" colspan="2">Closing stand up</td>
                        </tr>

                        <tr>
                            <td class="schedule-time">5:00pm</td>
                            <td class="combined-track" colspan="2"><em>Workshops finish</em></td>
                        </tr>

                        <tr>
                            <td class="schedule-time">6:00pm</td>
                            <td class="phunconf-track" colspan="2">
                                Sydney's famous PHUNCONF 5.0
                            </td>
                        </tr>

                        <tr>
                            <td class="schedule-time">9:00pm</td>
                            <td class="social-track" colspan="2">
                                <h3>Post conference social</h3>
                                <p>Most of our attendees continue on with an informal social event nearby.</p>
                            </td>
                        </tr>

                    </tbody>
                </table>
            </section>
        </div>
    </div>
</div>
