
<div id="main">
    <div class="container">

        <div class="container sponsor gold-sponsor">
            <section>
                <ul class="featured">
                    <li><p><a href="company-url">Sponsor</a></p>
                        <a href="company-url">
                            <img class="team" src="/img/team/dave.jpg" alt="company-url"/>
                        </a>
                    </li>
                    <li><p><a href="company-url">Sponsor</a></p>
                        <a href="company-url">
                            <img class="team" src="/img/team/dave.jpg" alt="company-url"/>
                        </a>
                    </li>
                    <li><p><a href="company-url">Sponsor</a></p>
                        <a href="company-url">
                            <img class="team" src="/img/team/dave.jpg" alt="company-url"/>
                        </a>
                    </li>
                    <li><p><a href="company-url">Sponsor</a></p>
                        <a href="company-url">
                            <img class="team" src="/img/team/dave.jpg" alt="company-url"/>
                        </a>
                    </li>
                </ul>
            </section>
        </div>
        <div class="container sponsor silver-sponsor">
            <section>
                <ul class="featured">
                    <li><p><a href="company-url">Company Name</a></p>
                        <a href="company-url">
                            <img class="team" src="/img/team/dave.jpg" alt="company-url"/>
                        </a>
                    </li>
                </ul>
            </section>
        </div>
        <div class="container sponsor bronze-sponsor">
            <section>
                <ul class="featured">
                    <li><p><a href="company-url">Company Name</a></p>
                        <a href="company-url">
                            <img class="team" src="/img/team/dave.jpg" alt="company-url"/>
                        </a>
                    </li>
                </ul>
            </section>
        </div>
    </div>
</div>


<!-- Banner -->

<div id="banner">
    <div class="container">
        <section>
            <header>
                <h2>Thanks again to all our sponosrs</h2>
                <span class="byline">We really appreciate your support</span>
            </header>
        </section>
    </div>
</div>