
<div id="main">

    <div class="container">

        <p>
            SydPHP runs Phunconf with the goal of making it as accessible to the community as possible.  This wouldn't be at all achievable without the kind generosity of our sponsors.
        </p>

        <p>
            If your company is interested in sponsoring Phunconf we'd love to hear from you.<br>Please send us an email at: phunconf &lt;at&gt; sydphp &lt;dot&gt; org.
        </p>

        <?php /* <section>
            <div id="sponsorNow" class="u12">
                <a href="#" target="_blank" class="button">Sponsor PHUNCONF Today!</a>
            </div>
        </section>*/ ?>


    </div>

    <div class="container">

        <script type="text/javascript">
            $(document).ready( function() {
                $('#tab-container').easytabs({
                    animate: true,
                    animationSpeed: 500,
                    updateHash: false
                });
            });
        </script>

        <div id="tab-container" class='tab-container'>
            <ul class='etabs'>
                <li class='tab'><a href="#sponsors">Sponsors</a></li>
                <li class='tab'><a href="#special-thanks-tab">Special Thanks</a></li>
                <li class='tab'><a href="#prize-sponsors-tab">Prizes</a></li>
            </ul>
            <div class='panel-container'>
                <div id="sponsors">
                    <div class="sponsor gold-sponsor">
                        <section>
                            <h1>Our Gold Sponsors</h1>
                            <ul class="featured">
                                <li><p><a target="_blank" href="http://4mation.com.au">4mation Technologies</a></p>
                                    <div class="sponsor-logo">
                                        <span class="vertical-helper"></span>
                                        <a target="_blank" href="http://4mation.com.au">
                                            <img class="team" src="/img/sponsors/4mation-technologies.png" alt="4mation Technologies"/>
                                        </a>
                                    </div>
                                </li>
                                <li><p><a target="_blank" href="http://www.theiconic.com.au">THE ICONIC</a></p>
                                    <div class="sponsor-logo">
                                        <span class="vertical-helper"></span>
                                        <a target="_blank" href="http://www.theiconic.com.au">
                                            <img class="team" src="/img/sponsors/iconic_logo.jpg" alt="THE ICONIC"/>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </section>
                    </div>
                    <div class="sponsor silver-sponsor">
                        <section>
                            <h1>Our Silver Sponsors</h1>
                            <ul class="featured">
                                <li><p><a target="_blank" href="http://lanyardsystems.com/">Lanyard Systems</a></p>
                                    <div class="sponsor-logo">
                                        <span class="vertical-helper"></span>
                                        <a target="_blank" href="http://lanyardsystems.com/">
                                            <img class="team" src="/img/sponsors/lanyardsystems.png" width="150px" height="150px" alt="Lanyard Systems"/>
                                        </a>
                                    </div>
                            </ul>
                        </section>
                    </div>
                    <div class="sponsor bronze-sponsor">
                        <section>
                            <h1>Our Bronze Sponsors</h1>
                            <ul class="featured">
                                <li><p><a target="_blank" href="http://developers.braintreepayments.com">Braintree_dev</a></p>
                                    <div class="sponsor-logo">
                                        <span class="vertical-helper"></span>
                                        <a target="_blank" href="http://developers.braintreepayments.com">
                                            <img class="team" src="/img/sponsors/braintree_dev.png" alt="Braintree_dev"/>
                                        </a>
                                    </div>
                                </li>

                                <li><p><a target="_blank" href="http://www.zend.com">Zend</a></p>
                                    <div class="sponsor-logo">
                                        <span class="vertical-helper"></span>
                                        <a target="_blank" href="http://www.zend.com">
                                            <img class="team" src="/img/sponsors/zend_logo.jpg" alt="Zend"/>
                                        </a>
                                    </div>
                                </li>

                                <li><p><a target="_blank" href="http://www.silverstripe.com/">SilverStripe</a></p>
                                    <div class="sponsor-logo">
                                        <span class="vertical-helper"></span>
                                        <a target="_blank" href="http://www.silverstripe.com/">
                                            <img class="team" src="/img/sponsors/SilverStripe_300_dark.png" alt="SilverStripe"/>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </section>
                    </div>

                    <div class="sponsor bronze-sponsor sponsor-large">
                        <section>
                            <ul class="featured">
                                <li><p><a target="_blank" href="https://www.eventbrite.com/e/mastercard-masters-of-code-competition-sydney-australia-tickets-14360074369/">
                                        MasterCard: Masters of Code Powered by AngelHack</a></p>
                                    <div class="sponsor-logo">
                                        <span class="vertical-helper"></span>
                                        <a target="_blank" href="https://www.eventbrite.com/e/mastercard-masters-of-code-competition-sydney-australia-tickets-14360074369/">
                                            <img class="team" src="/img/sponsors/angelhack.png" alt="MasterCard: Masters of Code Powered by AngelHack"/>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </section>
                    </div>
                </div>
                <div id="special-thanks-tab">
                    <h2>
                        We are truly grateful to the following individuals who have each contributed a community
                        sponsorship ticket towards the Phunconf event!
                    </h2>

                    <ul class="special-thanks">
                        <?php
                        $sponsors = array('Wil Brown' => ['LimeCanvasWil'],
                            'Scott Huntly' => ['MillerTafeScott'],
                            'Ben Corlett' => ['ben_corlett'],
                            'Michael Restuccia' => ['findercomau'],
                            'Sharleen Elmasri' => ['chillidee'],
                            'Robyn Stanley' => ['rumpledelf', 'dictphotos'],
                        );
                        foreach ($sponsors as $name => $handles) : ?>
                            <li>
                                <?=$name?>
                                <br />
                                <?php foreach ($handles as $handle) : ?>
                                    <a href="http://www.twitter.com/<?=$handle?>">@<?=$handle?></a>
                                <?php endforeach; ?>
                                <br /><img src="/img/logos/twitter.png" width="32px" height="32px" />
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div id="prize-sponsors-tab">
                    <h2>
                        Prizes for the event have been kindly donated by:
                    </h2>

                    <ul class="prize-sponsors">
                        <?php
                        $prizeSponsors = array(
                            'Zend' =>
                                ['logo' => 'zend_logo.jpg', 'url' => 'http://www.zend.com/'],
                            'Pluralsight' =>
                                ['logo' => 'pluralsight-medium.png', 'url' => 'http://www.pluralsight.com/'],
                            'JetBrains' =>
                                ['logo' => 'logo_jetbrains.png', 'url' => 'https://www.jetbrains.com/phpstorm/'],
                            'MasterCard: Masters of Code Powered by AngelHack' =>
                                ['logo' => 'angelhack.png', 'url' => 'https://www.eventbrite.com/e/mastercard-masters-of-code-competition-sydney-australia-tickets-14360074369/'],
                        );
                        foreach ($prizeSponsors as $name => $prizeData) : ?>
                            <li>
                                <a href="<?=$prizeData['url']?>"><?=$name?></a>
                                <br />
                                <img src="/img/sponsors/<?=$prizeData['logo']?>" alt="<?=$name?>"/>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Banner -->

<div id="banner">
    <div class="container">
        <section>
            <header>
                <h2>Thanks again to all our sponosrs</h2>
                <span class="byline">We really appreciate your support</span>
            </header>
        </section>
    </div>
</div>
