
<div id="main">

    <div class="container">

        <p>
            SydPHP runs Phunconf with the goal of making it as accessible to the community as possible.  This wouldn't be at all achievable without the kind generosity of our sponsors.
        </p>

        <p>
            If your company is interested in sponsoring Phunconf we'd love to hear from you.<br>Please send us an email at: phunconf &lt;at&gt; sydphp &lt;dot&gt; org.
        </p>

        <?php /* <section>
            <div id="sponsorNow" class="u12">
                <a href="#" target="_blank" class="button">Sponsor PHUNCONF Today!</a>
            </div>
        </section>*/ ?>


    </div>

    <div class="container">

        <div class="container sponsor gold-sponsor">
            <section>
                <h1>Our Gold Sponsors</h1>
                <ul class="featured">
                    <li><p><a target="_blank" href="http://4mation.com.au">4mation Technologies</a></p>
                        <div class="sponsor-logo">
                            <span class="vertical-helper"></span>
                            <a target="_blank" href="http://4mation.com.au">
                                <img class="team" src="/img/sponsors/4mation-technologies.png" alt="4mation Technologies"/>
                            </a>
                        </div>
                    </li>

                    <li><p><a target="_blank" href="http://www.theiconic.com.au">THE ICONIC</a></p>
                        <div class="sponsor-logo">
                            <span class="vertical-helper"></span>
                            <a target="_blank" href="http://www.theiconic.com.au">
                                <img class="team" src="/img/sponsors/iconic_logo.jpg" alt="THE ICONIC"/>
                            </a>
                        </div>
                    </li>
                </ul>
            </section>
        </div>
        <?php /*<div class="container sponsor silver-sponsor">
            <section>
                <h1>Our Silver Sponsors</h1>
                <ul class="featured">
                    <li><p><a target="_blank" href=""></a></p>
                        <div class="sponsor-logo">
                            <span class="vertical-helper"></span>
                            <a target="_blank" href="">
                                <img class="team" src="/img/sponsors/?.png" alt=""/>
                            </a>
                        </div>
                </ul>
            </section>
        </div> */ ?>
        <div class="container sponsor bronze-sponsor">
            <section>
                <h1>Our Bronze Sponsors</h1>
                <ul class="featured">
                    <li><p><a target="_blank" href="http://developers.braintreepayments.com">Braintree_dev</a></p>
                        <div class="sponsor-logo">
                            <span class="vertical-helper"></span>
                            <a target="_blank" href="http://developers.braintreepayments.com">
                                <img class="team" src="/img/sponsors/braintree_dev.png" alt="Braintree_dev"/>
                            </a>
                        </div>
                    </li>
                </ul>
            </section>
        </div>
    </div>
</div>


<!-- Banner -->

<div id="banner">
    <div class="container">
        <section>
            <header>
                <h2>Thanks again to all our sponosrs</h2>
                <span class="byline">We really appreciate your support</span>
            </header>
        </section>
    </div>
</div>
