<!-- Intro -->
<div id="intro">
    <div class="container">
        <div class="row">

            <section class="6u">
                <header>
                    <h2>Phunconf 5.0</h2>
                </header>
                <div class="content">
                    <p>
                        The unconference is an evening event that has no prescribed schedule.
                        Instead, the organisers (with the assistance of subject matter experts
                        and guided by community interest) run a series of open circle discussions focusing
                        on knowledge sharing and peer learning. A wide range of topics are discussed and no
                        unconf is ever the same.
                    </p>
                </div>
                <header>
                    <h2>Workshops</h2>
                </header>
                <div class="content">
                    <p>
                        The workshops are a focused classroom style learning experience
                        where numbers are limited for the benefit of those attending. Workshop
                        sessions are led by industry leaders including SydPHP's very own Dave
                        Clark (Zend Certified Training Partner). A full workshop schedule will be
                        announced soon and will feature topics including Web applications at
                        Scale and a PHP Masterclass.
                    </p>
                </div>
                <header>
                    <h2>Code Retreat</h2>
                </header>
                <div class="content">
                    <p>
                        Phunconf’s code retreat is run by Szabolcs Palmer (Senior Platform
                        Engineer at Yahoo!7) providing an opportunity for developers to hone
                        their unit testing skills. Developers will complete a series of simple code
                        challenges aimed at perfecting the art of test driven development. This
                        is a unique and hands on pair programming experience.
                    </p>
                </div>
            </section>

            <section class="4u">

                <span class="image">
                    <img class="promo" src="img/phunconf4.0-group1.jpg" alt="">
                </span>

                <span class="image">
                    <img class="promo" src="img/phunconf4.0-circle.jpg" alt="">
                </span>

                <span class="image">
                    <img class="promo" src="img/phunconf4.0-circle2.png" alt="">
                </span>

            </section>
        </div>
    </div>
</div>