<!-- Intro -->
<div id="intro">
    <div class="container">
        <div class="row">

            <section class="12u">
                <header>
                    <h1>Workshops</h1>
                </header>

                <p>
                    To celebrate Phunconf's 5th birthday there is also a series of workshops and a code retreat available to attendees.
                    Both workshops and code retreat run during the day on February 5th and tickets include entry to the evening unconference.
                </p>
            </section>
        </div>
        <div class="row">
            <section class="7u cell-float">
                <header>
                    <h2>Code Retreat</h2>
                </header>

                <div class="content">
                    <p>
                        Phunconf’s code retreat is run by Szabolcs Palmer (Senior Platform
                        Engineer at Yahoo!7) providing an opportunity for developers to hone
                        their unit testing skills. Developers will complete a series of simple code
                        challenges aimed at perfecting the art of test driven development. This
                        is a unique and hands on pair programming experience.
                    </p>
                </div>
            </section>

            <section class="5u cell-float">
                <header>
                    <h3>Szabolcs Palmer</h3>
                </header>

                <div class="content">
                    <p>
                        Phunconf’s code retreat is run by Szabolcs Palmer (Senior Platform
                        Engineer at Yahoo!7) providing an opportunity for developers to hone
                        their unit testing skills. Developers will complete a series of simple code
                        challenges aimed at perfecting the art of test driven development. This
                        is a unique and hands on pair programming experience.
                    </p>
                </div>
            </section>
        </div>

        <div class="row">
            <section class="5u cell-float">
                <header>
                    <h3>Dave Clark</h3>
                </header>

                <div class="content">
                    <p>
                        Phunconf’s code retreat is run by Szabolcs Palmer (Senior Platform
                        Engineer at Yahoo!7) providing an opportunity for developers to hone
                        their unit testing skills. Developers will complete a series of simple code
                        challenges aimed at perfecting the art of test driven development. This
                        is a unique and hands on pair programming experience.
                    </p>
                </div>
            </section>

            <section class="7u cell-float">
                <header>
                    <h2>PHP Masterclass</h2>
                </header>

                <div class="content">
                    <p>
                        Phunconf’s code retreat is run by Szabolcs Palmer (Senior Platform
                        Engineer at Yahoo!7) providing an opportunity for developers to hone
                        their unit testing skills. Developers will complete a series of simple code
                        challenges aimed at perfecting the art of test driven development. This
                        is a unique and hands on pair programming experience.
                    </p>
                </div>
            </section>
        </div>

        <div class="row">
            <section class="5u cell-float">
                <header>
                    <h2>PHP security</h2>
                    <h4>AKA: <em>I'm in ur s3rvs h4cking ur c0dez</em></h4>
                </header>

                <div class="content">
                    <p>
                        Whether building a new application or maintaining an old one, security is always something a developer has to be mindful of.  This session
                        This session will focus on identifying and fixing vulnerabilities in your code.
                        Attendees to this workshop will walk away with the increased ability to audit security exploits, fix them, and execute their release into the wild.
                        Bring your own device -- internet connectivity and power will be provided
                    </p>
                </div>
            </section>
gi
            <section class="7u cell-float">
                <header class="centered">
                    <h3>Katie McLaughlin <br>&amp;<br> Jack Skinner</h3>
                </header>

                <div class="content">
                    <p>
                        Phunconf’s code retreat is run by Szabolcs Palmer (Senior Platform
                        Engineer at Yahoo!7) providing an opportunity for developers to hone
                        their unit testing skills. Developers will complete a series of simple code
                        challenges aimed at perfecting the art of test driven development. This
                        is a unique and hands on pair programming experience.
                    </p>
                </div>
            </section>
        </div>

        <div class="row">
            <section class="5u cell-float">
                <header>
                    <h3>Dave Clark</h3>
                </header>

                <div class="content">
                    <p>
                        Phunconf’s code retreat is run by Szabolcs Palmer (Senior Platform
                        Engineer at Yahoo!7) providing an opportunity for developers to hone
                        their unit testing skills. Developers will complete a series of simple code
                        challenges aimed at perfecting the art of test driven development. This
                        is a unique and hands on pair programming experience.
                    </p>
                </div>
            </section>

            <section class="7u cell-float">
                <header>
                    <h2>PHP at Scale</h2>
                </header>

                <div class="content">
                    <p>
                        Phunconf’s code retreat is run by Szabolcs Palmer (Senior Platform
                        Engineer at Yahoo!7) providing an opportunity for developers to hone
                        their unit testing skills. Developers will complete a series of simple code
                        challenges aimed at perfecting the art of test driven development. This
                        is a unique and hands on pair programming experience.
                    </p>
                </div>
            </section>
        </div>
        <div class="row">
            <section ckass="12u">
                <div class="content">
                    <p>
                        Workshops and Code Retreat will run during the day (9-5pm) at the Y Hotel Conference Centre, 5-1 Wentworth Ave, Sydney.
                        Attendance is ticketed separately to the evening unconference (but includes access for those attending workshops etc.)
                        A full conference schedule will be posted soon.
                    </p>
                </div>
            </section>
        </div>

    </div>
</div>